### ISSUE TITLE
Can't use pico-fido-tool.py secure function

### ISSUE THREAD

**Issue by M11158002** [polhenarejos/pico-fido#23]
An error occurred while enabling the secure feature using pico-fido-tool.py

```shell
Pico Fido Tool v1.5
Author: Pol Henarejos
Report bugs to https://github.com/polhenarejos/pico-fido/issues


Traceback (most recent call last):
  File "/home/user/Documents/pico/pico-fido/tools/pico-fido-tool.py", line 469, in <module>
    run()
  File "/home/user/Documents/pico/pico-fido/tools/pico-fido-tool.py", line 466, in run
    main(args)
  File "/home/user/Documents/pico/pico-fido/tools/pico-fido-tool.py", line 458, in main
    secure(vdr, args)
  File "/home/user/Documents/pico/pico-fido/tools/pico-fido-tool.py", line 416, in secure
    vdr.enable_device_aut()
  File "/home/user/Documents/pico/pico-fido/tools/pico-fido-tool.py", line 375, in enable_device_aut
    ct = self.get_skey()
         ^^^^^^^^^^^^^^^
  File "/home/user/Documents/pico/pico-fido/tools/pico-fido-tool.py", line 371, in get_skey
    ct = self.encrypt_chacha(self._get_key_device())
                             ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/Documents/pico/pico-fido/tools/pico-fido-tool.py", line 367, in _get_key_device
    return skey.get_secure_key()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/Documents/pico/pico-fido/tools/secure_key/windows.py", line 44, in get_secure_key
    return get_d(key.encode())
                 ^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'encode'
```

**Comment by polhenarejos** [comment]
Open your python

- 1st:
```
DOMAIN = "PicoKeys.com"
USERNAME = "Pico-Fido"

import keyring

key = keyring.get_password(DOMAIN, USERNAME)
```
Does `key` return `NoneType`  or raises an exception?

- 2nd:
```
import keyring
from cryptography.hazmat.primitives.serialization import Encoding, PrivateFormat, NoEncryption, load_pem_private_key
from cryptography.hazmat.primitives.asymmetric import ec
pkey = ec.generate_private_key(ec.SECP256R1())
keyring.set_password("test", "test", pkey.private_bytes(Encoding.PEM, PrivateFormat.PKCS8, NoEncryption()).decode())
key = keyring.get_password(DOMAIN, USERNAME)
``` 
Does `key` return `NoneType`  or raises an exception?

**Comment by polhenarejos** [comment]
Sorry, the 2nd is wronge. Please use this:
```
import keyring
DOMAIN = "PicoKeys.com"
USERNAME = "Pico-Fido"
from cryptography.hazmat.primitives.serialization import Encoding, PrivateFormat, NoEncryption, load_pem_private_key
from cryptography.hazmat.primitives.asymmetric import ec
pkey = ec.generate_private_key(ec.SECP256R1())
keyring.set_password(DOMAIN, USERNAME, pkey.private_bytes(Encoding.PEM, PrivateFormat.PKCS8, NoEncryption()).decode())
key = keyring.get_password(DOMAIN, USERNAME)
```

**Comment by polhenarejos** [comment]
But in the 3rd code, is `key` of `NoneType` or exists?

**Comment by polhenarejos** [comment]
Now that you've generated the key, does `backup` work?
