### ISSUE TITLE
Issue in pico-fido-tool.py

### ISSUE THREAD

**Issue by Aadinthosh** [polhenarejos/pico-fido#42]
I am facing an issue using the pico-fido-tool.py file while executing the attestation command 'csr'. I have the mentioned exception occurred during the execution of the python file under tools folder  below

Traceback (most recent call last):
  File "D:\IoT-Projects\fido-activity\pico-fido\tools\pico-fido-tool.py", line 475, in <module>
    run()
  File "D:\IoT-Projects\fido-activity\pico-fido\tools\pico-fido-tool.py", line 472, in run
    main(args)
  File "D:\IoT-Projects\fido-activity\pico-fido\tools\pico-fido-tool.py", line 468, in main
    attestation(vdr, args)
  File "D:\IoT-Projects\fido-activity\pico-fido\tools\pico-fido-tool.py", line 438, in attestation
    j = get_pki_data('csr', data=data)
  File "D:\IoT-Projects\fido-activity\pico-fido\tools\pico-fido-tool.py", line 73, in get_pki_data
    response = urllib.request.urlopen(req)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\urllib\request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\urllib\request.py", line 525, in open
    response = meth(req, response)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\urllib\request.py", line 634, in http_response
    response = self.parent.error(
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\urllib\request.py", line 563, in error
    return self._call_chain(*args)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\urllib\request.py", line 496, in _call_chain
    result = func(*args)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\urllib\request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 500: Internal Server Error

**Comment by polhenarejos** [comment]
Fixed at backend.
